### ISSUE TITLE
petclinic

### ISSUE THREAD

**Issue by mikeavila** [elvisaronsp/EALAT700#1]
You have forked petclinic from my GitHub project. Unfortunately there is data in the fork you created that requires a license. I am licensed but you are not. Use of the data without a license is illegal. You either need to delete your copy of the petclinic project or delete the data subdirectory. Failure to do so will result in my notifying the appropriate people of your illegal activity.

Today is Friday April 15, 2016. I expect this issue to be resolved by Friday April 22, 2016 or I will notify the proper people to take action against you. I hope that is not necessary. 

Thank you for your cooperation in this matter.

**Comment by elvisaronsp** [comment]
Hi, i just saw it now!
i had no idea that could create this problem.
I am a student ad i am trying to learn php and understand it better.

dont worry i did not used your app and deleted it.

once again I apologyze!

Thanks
